apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-nginx-deployment
  template:
    metadata:
      labels:
        app: simple-nginx-deployment
    spec:
      containers:
      - name: simple-nginx-deployment
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: local-volume
      volumes:
        - name: local-volume
          persistentVolumeClaim:
            claimName: pvclaim
        
