apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvalume
  labels:
     type: local
spec:
  capacity:
    storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
     path: "/Users/kumar/Projects/SimpleKubernetesDeployment/html"

