apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclaim
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
